server:
  port: 8000
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  address: 0.0.0.0

spring:
  main:
    allow-circular-references: true  # 允许循环依赖
  config:
    import:
      - application-dal.yaml
      - application-monitor.yaml

database:
  name: dbname

security:
  jwt:
    key: "secret_key"

logging:
  level:
    root: info